version: "3.9"
services:
  move-api:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    expose:
      - "3000"
    logging:
      options:
        max-file: "5"
        max-size: "50m"
