version: "3.9"
services:
  api-nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/api-violence.conf:/etc/nginx/conf.d/default.conf
    logging:
      options:
        max-file: "3"
        max-size: "50m"
  test-api:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    expose:
      - "3000"
    logging:
      options:
        max-file: "5"
        max-size: "50m"
